project:
  type: book
  output-dir: _book
book:
  title: "An Introduction to R"
  subtitle: "1st Edition"
  author: 
    - "Konstantinos I. Bougioukas, PhD"
    - "Anna-Bettina Haidich, Associate Professor"
  date: "August 7, 2022"
  cover-image: images/cover.png
  repo-url: https://github.com/bougioukas/introR
  chapters:
    - index.qmd
    - part: "Basics"
      chapters:
        - introduction.qmd

    - part: "Special Topics"
      chapters:
        - lab1.qmd

    - references.qmd
  
  page-footer: 
    left: "Copyright 2022, Konstantinos I. Bougioukas" 

bibliography: references.bib

filters:
  - lightbox
lightbox: auto

format:
  html:
    theme: cosmo
    fontsize: 1.2em
    linestretch: 1.8
    link-external-newwindow: true
    code-link: true
    number-depth: 2
editor: visual